name: KotobaAnnounce
main: org.kotobaminers.kotobaannounce.kotobaannounce.KotobaAnnounce
version: ${git.commit.id.describe}
authors: [Thasan, kai_f]
website: http://www.kotobaminers.org/plugins/KotobaAnnounce
database: false
commands:
  kotobaannounce:
    description: Control announcements
    aliases: [announce, ka]
    permission: kotobaannounce.
    usage: Type "/announce help" to see announce commands

